// Generated by CoffeeScript 1.7.1
(function() {
  var MyRecord, Record,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Record = require('../lib/record');

  MyRecord = (function(_super) {
    __extends(MyRecord, _super);

    function MyRecord() {
      return MyRecord.__super__.constructor.apply(this, arguments);
    }

    MyRecord["extends"] = {
      dummy: function() {}
    };

    MyRecord.methods = {
      saveMyDay: function() {}
    };

    return MyRecord;

  })(Record);

  module.exports = MyRecord;

}).call(this);
